### ISSUE TITLE
Is the behavior of maximum year limit in syslog parser what is desired?

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1114]
While working on https://github.com/log2timeline/plaso/issues/1108 I've noticed

That when the file modification time is 2016 and current year is 2016 [the maximum year limit in syslog parser](https://github.com/log2timeline/plaso/blob/master/plaso/parsers/syslog.py#L194) forces the date and time values in the [cron test file](https://github.com/log2timeline/plaso/blob/master/test_data/syslog_cron.log) to become 2016, where seeing the jump in the files one could expect 2017.

@Onager let's chat what the most appropriate UX would be here.

One option is to fail any date and time value after maximum year and generate extraction errors.

**Comment by Onager** [comment]
Clamping the file year to file modification year is definitely what I intended, and I disagree that you'd expect year values for events occurring in 2017 in a file that was last modified in 2016.

Producing errors isn't correct either - the last events in the cron test file should be interpreted as 2016, it's the events prior to that point that have the wrong year value, which should be 2015, not 2016.  

We could possible resolve this by parsing the file backwards, rather than starting at the oldest entries in the log.

**Comment by Onager** [comment]
No discussion for a year, closing out.

**Comment by joachimmetz** [comment]
Should be resolved by https://github.com/log2timeline/plaso/issues/4266
