### ISSUE TITLE
No webhistory in Win7 Encaase Image

### ISSUE THREAD

**Issue by brasco2k** [log2timeline/plaso#1251]
Plaso version: 1.5.1
Operating system Plaso is running on: Ubuntu (SIFT workstation, obtained from the SANS institute)

**Description of problem:**

Hi there,
I am running Log2Timeline on a Windows-7-Enterprise-Image (E01). I get a lot of results, however, the Internet History (IE, Chrome) is not being parsed / recognized. Analyzing the Internet History with other tools (e. g. EnCase) reveals Internet History quite detailed.

I was running log2timeline first without handing over any parsers. Afterwards, I explicitly set the parser "win7"; however, the total number events was less and also no internet history contained.

Does anybody have an idea why the internet history is not being recognized and how I could fix this issue? Please let me know if you need further information.

**Comment by theraven1982** [comment]
Not meant to hijack the thread, but I have a similar issue with the registry. I've explicitly enabled the winreg parser for a Windows 10 image (EWF), and it does not find any registry keys/info. 

Does your logfile/plaso storage contain any info regarding the parsers or errors? Add the --debug flag to log2timeline, and check the output of pinfo <plaso-storage-file> maybe.

I can't find any registry info (e.g. a mention of the registry files) in the debug logfile. Running pinfo shows all the winreg parers/plugins to be enabled. No errors stored. 

Running the docker image (1.5.1) on ubuntu. 

Btw, I'm really happy you provide the docker image for running plaso, it's awesome! I tried upgrading the docker to the latest development version to see if the problem disappears, but due to some dependency issues didn't succeed.

**Comment by joachimmetz** [comment]
Sry for the slower response from our side. This is likely related to https://github.com/log2timeline/plaso/issues/1121, and processing errors causing tasks to fail. What does the error log tell you?

**Comment by theraven1982** [comment]
No problem at all.
In the plaso file there are no stored errors. I don't see any obvious errors in the logfile; I do see a lot of abandoned tasks though.

I've uploaded the log [here](https://paste.ee/p/7FPn7)

Let me know if there's something else I can do to help resolving this issue.

**Comment by joachimmetz** [comment]
@Onager is current working on some change to address abandoning tasks https://github.com/log2timeline/plaso/issues/1200

but our time to work on this is limited at the moment

**Comment by joachimmetz** [comment]
Also related: https://github.com/log2timeline/plaso/issues/1073

**Comment by joachimmetz** [comment]
Please try if this persists in the latest pre release https://github.com/log2timeline/plaso/releases. Closing this issue since similar sounding issues have been fixed.
