### ISSUE TITLE
Make L2tcsv timestamps sortable 

### ISSUE THREAD

**Issue by apapadop** [log2timeline/plaso#132]
The current timestamp format of the L2tcsv psort.py output (03/25/2015,13:35:34) does not allow for easy sorting by standard tools (e.g. GNU sort).

It would be useful to have timestamps printed in a sortable way, e.g. 2015/03/25, 13:35:34

**Comment by kiddinn** [comment]
This will not be fixed since the l2t_csv format is an "old" format that is considered to be a legacy format. Changing it at this point will brake all the tools that have been created to parse it.

However I suggest that you instead of using l2t_csv use the default output of plaso, the default CSV format of plaso, which is much "nicer" to sorting using standard GNU tools like sort.

Also using psort gives you a sorted output file...
