### ISSUE TITLE
Update Chrome History parser to support new format

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1425]
Update Chrome History parser to support new format.

```
Message : unable to run query: SELECT id, full_path, url,
                     start_time, received_bytes, total_bytes,state FROM
                     downloads on database with error: no such column:
                     full_path
Parser chain : sqlite/chrome_history
Path specification : type: OS, location:
```

Note to self, double check schema matching

Additional issue is might be that the error is generated because the old query is also applied. Let's make this more intelligent.

* [x] dependencies:
  * https://codereview.appspot.com/333560043/
  * https://codereview.appspot.com/335450043/
* [x] change parser not to generate extraction error
  * https://codereview.appspot.com/336470043/
* [x] change parser to work with Chrome 63
  * works with specimen https://github.com/dfirlabs/chrome-specimens/blob/master/history/History-63.0.3239.108
  * but not with 63.0.3239.132?
  * https://codereview.appspot.com/337500043/

**Comment by joachimmetz** [comment]
@tomchop who indicated to work on this

**Comment by tomchop** [comment]
The schema check seems to be made on the schema [name](https://github.com/log2timeline/plaso/blob/master/plaso/parsers/sqlite_plugins/interface.py#L159) only.

If we want to support multiple versions of the Chrome History file we could either create several parsers (one for each version with differing schema), or otherwise try to parse the SQLite database with all known schemas and keep the results of the one that works. Thoughts?

**Comment by tomchop** [comment]
I will go for the second alternative (testing several schemas for a given database) since we'll have better control over error generation.

**Comment by tomchop** [comment]
So, it turns out the structure of the new SQLite database is already parsed in [ParseNewFileDownloadedRow](https://github.com/log2timeline/plaso/blob/c54c84bda4e4c90dcb7279dbf6e086b1c55faf77/plaso/parsers/sqlite_plugins/chrome.py#L293). The reason we se an error is that all items of `QUERY` are being parsed sequentially, and one of the two queries for Chrome downloads history will fail, which will systematically generate an error. I tested this on History files of both Chrome 61 and Chrome 51 (~April 2016) with log2timeline from 1c2cd711 and both generate the same error.

If this systematic error generation is not acceptable, we should open a new issue and revamp the way SQLite databases are parsed in `sqlite_plugins/interface.py` or `parsers/sqlite.py`.

**Comment by Onager** [comment]
@tomchop What's that status on this? Do you want to close this out, and add an issue to change the logic in the sqlite parser instead?

**Comment by joachimmetz** [comment]
@Onager @tomchop IMHO we should address this in the next release I'm fine taking this over if needed

**Comment by joachimmetz** [comment]
Newer format
```
CREATE TABLE downloads (id INTEGER PRIMARY KEY,guid VARCHAR NOT NULL,current_path LONGVARCHAR NOT NULL,target_path LONGVARCHAR NOT NULL,start_time INTEGER NOT NULL,received_bytes INTEGER NOT NULL,total_bytes INTEGER NOT NULL,state INTEGER NOT NULL,danger_type INTEGER NOT NULL,interrupt_reason INTEGER NOT NULL,hash BLOB NOT NULL,end_time INTEGER NOT NULL,opened INTEGER NOT NULL,referrer VARCHAR NOT NULL,site_url VARCHAR NOT NULL,tab_url VARCHAR NOT NULL,tab_referrer_url VARCHAR NOT NULL,http_method VARCHAR NOT NULL,by_ext_id VARCHAR NOT NULL,by_ext_name VARCHAR NOT NULL,etag VARCHAR NOT NULL,last_modified VARCHAR NOT NULL,mime_type VARCHAR(255) NOT NULL,original_mime_type VARCHAR(255) NOT NULL, last_access_time INTEGER NOT NULL DEFAULT 0, transient INTEGER NOT NULL DEFAULT 0);
CREATE TABLE downloads_url_chains (id INTEGER NOT NULL,chain_index INTEGER NOT NULL,url LONGVARCHAR NOT NULL, PRIMARY KEY (id, chain_index) );
```

**Comment by joachimmetz** [comment]
One option is to compare the schema and have different plugins per schema?

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/333560043/
https://codereview.appspot.com/335450043/

**Comment by joachimmetz** [comment]
ParseNewFileDownloadedRow introduced in https://github.com/log2timeline/plaso/commit/c0644d2ac26d5a99e0e43fe27b1aeac945052d89

https://codereview.appspot.com/8873043/

**Comment by joachimmetz** [comment]
Generated various specimens of Chrome History files: https://github.com/dfirlabs/chrome-specimens/tree/master/history
