### ISSUE TITLE
Unable to decipher comment

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#161]
I moved some code around and came across this comment:
https://github.com/log2timeline/plaso/blob/master/plaso/parsers/text_parser.py#L95

Both Daniel and me are wondering what you mean by it.

Also see: https://codereview.appspot.com/218530043/

**Comment by kiddinn** [comment]
this is a very good question..... and this is one of the things I sometimes point out in code reviews (like the one we had today).... please make your TODO's more clear so that when you come back to them 6 months later you'll actually remember yourself what you meant....

And that answers this question since I have no idea what this comment means ;) and yes, it clearly should have been more clear, that is obvious now (captain hindsight strikes again).

And in the future we should be more careful about TODO's, point them towards issues on github or otherwise make it clear what our intention is with these TODO's.

I vote for striking this TODO out of the code, since at this point no one knows what the background is nor what it is asking about.

**Comment by kiddinn** [comment]
comment removed
