### ISSUE TITLE
Add tests for winreg path filters

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1668]
In #1660 the winreg plugin filter and test were different, causing a test to pass while the plugin was broken.

Winreg plugin tests need to be refactored so that they catch such issues.

**Comment by joachimmetz** [comment]
The filter is applied elsewhere, the same as format specification. A beter solution is to add a test for the filter instead.

**Comment by joachimmetz** [comment]
"Refactor winreg plugin tests to reduce duplication to Test winreg filters" this over optimizing. Also this will make the tests no longer independent from the code. Common best practice is to not mix production code with the tests. The thing that needs to be addressed here is adding tests for the path filters.

**Comment by joachimmetz** [comment]
A first start in: https://codereview.appspot.com/333570043

**Comment by Onager** [comment]
> A beter solution is to add a test for the filter instead.
I don't agree, we're not testing the filtering code, this just ends up testing that a string in the parser is equal to some value. This could just as easily be "testFilters = frozenset(..); assertEqual(plugin.FILTERS, testfilter).

> this over is optimizing. 
Again, I don't agree. Removing the duplication of these key paths isn't for optimizing performance, it's to minimize bugs. 

>Also this will make the tests no longer independent from the code. Common best practice is to not mix production code with the tests. 
I'm not sure what you mean here, but usually "don't mix production code with tests" seems to mean "don't contort code just to make it testable", but extracting the key path to a separate variable doesn't dramatically change the plugin code, but drastically increases its testability.

> The thing that needs to be addressed here is adding tests for the path filters.
The filter tests you've proposed here would not have caught the issue in #1660. Both the filter test and plugin would just have been updated together, the parser test works, and the plugin is still broken.

**Comment by joachimmetz** [comment]
> Removing the duplication of these key paths isn't for optimizing performance, it's to minimize bugs.

Optimization is not only regarding performance, also for size of code, maintenance.

You're proposal in https://codereview.appspot.com/339260043/diff/1/tests/parsers/winreg_plugins/sam_users.py is not addressing this issue for most Registry plugins 

> The filter tests you've proposed here would not have caught the issue in #1660. 

It does, try changing the path in the filter

Since you use the same path for both the plugin and tests. The fake Registry sets up the same path as the plugin.

1. this does not work for all filters
2. a filter can define more paths you're not testing
3. if the path is wrong the same risk is there that test will pass, since we're using a fake registry in some tests

> I'm not sure what you mean here, but usually "don't mix production code with tests" seems to mean "don't contort code just to make it testable",

By directly using the path in the filter you don't independently check it.

**Comment by joachimmetz** [comment]
Merged https://github.com/log2timeline/plaso/pull/1674, assigning to @Onager  to determine if more needs to be done for this issue.

**Comment by Onager** [comment]
The changes made should catch most of these sorts of errors for now.
