### ISSUE TITLE
Make ProcessInfo class work on OSX

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#175]
Per https://code.google.com/p/psutil/wiki/Documentation get_io_counters() doesn't exist on OSX.

**Comment by berggren** [comment]
Testing on OSX fails because get_io_counters from psutils is not available on that platform.

Results in:
AttributeError during this test. 
self.assertNotEqual(process_info_object.io_counters, None)

I have commented out this test and added a comment (and a TODO in the actual code). We should revisit if we really need this at all?

**Comment by kiddinn** [comment]
Added http://codereview.appspot.com/232220043

**Comment by kiddinn** [comment]
removed the io counter, this should be done now.
