### ISSUE TITLE
ISO analyse with Plaso

### ISSUE THREAD

**Issue by Lyro1** [log2timeline/plaso#2173]
This is just a simple question:

I would like to know if there is any way to analyse a *.iso* file directly with Plaso tools ? What is the easiest way to do so ?

**Comment by joachimmetz** [comment]
What type of "iso" file? Also see: https://en.wikipedia.org/wiki/ISO_image

**Comment by Lyro1** [comment]
An issue file that would be the result of a hard drive dump for forensic investigation.

**Comment by joachimmetz** [comment]
> An .iso file that would be the result of a hard drive dump for forensic investigation.

That does not help me, to help you answer your question. If pytsk/libtsk support the file system in the iso file, plaso like supports parsing the contents natively otherwise you'll have to extract/expose the content otherwise.

See here for supported file systems: https://github.com/log2timeline/dfvfs/wiki

**Comment by Lyro1** [comment]
Oh thanks that's exactly what I was searching for.
