### ISSUE TITLE
Question:  Where is the presets.py file found in the Windows version?

### ISSUE THREAD

**Issue by mark-hallman** [log2timeline/plaso#2201]
On the Windows version (20180930), where would I find the presets.py file? If it is not there, is there a similar file?  In the Linux version I have defined my own presets and  I would like to do the same on Windows.  

Thanks!

**Comment by Onager** [comment]
It's compiled into log2timeline.exe in the pyinstaller Windows release. You'd have to fork Plaso, make your changes and then re-package if you wanted a custom preset. We could switch the preset system to use a YAML file instead of a Python class which would make this easier, but there's no current feature request for that.

Alternatively, if the preset isn't sensitive, you can just add it to the main Plaso config here. That would be my preference, as it's a lost less work.

**Comment by joachimmetz** [comment]
Presets are found here: https://github.com/log2timeline/plaso/blob/master/plaso/parsers/presets.py

**Comment by joachimmetz** [comment]
There are ideas to move them into a configuration file: https://github.com/log2timeline/plaso/issues/1662

**Comment by joachimmetz** [comment]
No follow up from reporter, assuming question was answered.
