### ISSUE TITLE
log2timeline Distributed and Parallel Computing

### ISSUE THREAD

**Issue by garanews** [log2timeline/plaso#2293]
**Description of problem:**

Do you think it will be possible to run log2timeline over a cluster in order to speed up the generation of plaso?

**Comment by joachimmetz** [comment]
What cluster technology? For a distributed plaso disk/network IO and latency will be the biggest challenge.

**Comment by joachimmetz** [comment]
Eric the method you describe would mean adding distributed code to plaso. We've considered this before.

* Currently the unit of work is a file entry (file or directory).
* Mode 1 is how plaso currently works multi process (not multi thread because Python MT is inefficient due to the GIL).
* We use pyzmq and XLM-RPC for the communications. Both should be network ready. 

Now the challenge will be:
* how distributed workers interact with the foreman process
* how to read files from storage media, this currently requires a shared file system, how efficient is this IO wise
* how to write resulting "task storage" files (results), this currently would require a shared file system but the SQLite storage could be replaced by a network capable database

**Comment by garanews** [comment]
About cluster tecnology, I am thinking to DASK, so distribute load on different servers...

**Comment by joachimmetz** [comment]
@garanews I'm not familiar with DASK, and this is not a priority on my long list of things to do. I'm closing this issue. Reopen if you have implementation specific questions regarding plaso using DASK.
