### ISSUE TITLE
Why is there no x86 version for the past few releases?

### ISSUE THREAD

**Issue by kmarker** [log2timeline/plaso#2526]
I noticed there hasn't been a python 2.7 x86 release for the last few releases?  Why is that?

**Comment by joachimmetz** [comment]
> I noticed there hasn't been a python 2.7 x86 release for the last few releases? 

I assume you specifically mean [Windows PyInstaller packaged release](https://github.com/log2timeline/plaso/wiki/Windows-Packaged-Release) since technically there has been an Ubuntu 32-bit Python 2.7 release in GIFT PPA, a Windows 32-bit Python 2.7 release in [l2tbinaries](https://github.com/log2timeline/l2tbinaries), a Fedora 32-bit Python 2.7 release in COPR 

> Why is that?

We did not got around to it. Also who is still using 32-bit nowadays?

**Comment by joachimmetz** [comment]
No response from reporter in more than 10 days, closing issue.
