### ISSUE TITLE
Kali Linux installation: ImportError: No module named dfvfs.lib

### ISSUE THREAD

**Issue by evilcode1** [log2timeline/plaso#2676]
hey all ... 
im trying to use log2timeline.py and psort.py on my machine it's kali linux 

> Linux kali 4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux

tested on 2 kali machines and i got the same error : 
```
Traceback (most recent call last):
  File "/usr/local/bin/psteal.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==20190531', 'psteal.py')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/plaso-20190531-py2.7.egg/EGG-INFO/scripts/psteal.py", line 23, in <module>
    from plaso.cli import psteal_tool
  File "/usr/local/lib/python2.7/dist-packages/plaso-20190531-py2.7.egg/plaso/cli/psteal_tool.py", line 12, in <module>
    from dfvfs.lib import definitions as dfvfs_definitions
ImportError: No module named dfvfs.lib
```

**Comment by joachimmetz** [comment]
per issue template could you tell us how you installed plaso and its dependencies?
it looks like you did not install dfvfs which is a required dependency for plaso.

**Comment by evilcode1** [comment]
I just download it and run 
Python setup.py install !!
How to install dfvfs?

**Comment by joachimmetz** [comment]
setup.py will not install the dependencies for you, since typically this uses pip and this has messed up many system installations of people not aware of this before. Hence we do not have setup.py install depdencies for you.

Installation instructions can be found here https://plaso.readthedocs.io/en/latest/sources/user/Users-Guide.html 

Or if you're knowing what you are doing: https://plaso.readthedocs.io/en/latest/sources/developer/Developing-Virtualenv.html

I'm closing this issue marking as invalid, since this is an issue specific to your installation not to plaso.
