### ISSUE TITLE
Consider removing FORMAT_STRING_ALTERNATIVE

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#2837]
Some formatters define `FORMAT_STRING_ALTERNATIVE` this seems to be used by https://github.com/log2timeline/plaso/blob/master/plaso/formatters/winreg.py#L60. This seems to have been implemented in the beginning https://github.com/log2timeline/plaso/commits/be4c2cd299d0cbd14fcfd12993a889e359239779/plaso/formatters/winreg.py

Unclear what purpose this has. @kiddinn do you recall what the purpose of `FORMAT_STRING_ALTERNATIVE` was/is?

**Comment by kiddinn** [comment]
you can see this was from the get-go: https://codereview.appspot.com/7069058/patch/8004/5026 

I'm trying to recall why this was the case, but IIRC you can see:

```
    if 'key_path' in event_values:
      format_string = self.FORMAT_STRING
    else:
      format_string = self.FORMAT_STRING_ALTERNATIVE
```

And the original was:

```
    if hasattr(event_object, 'keyname'):
        self.format_string = self.FORMAT_STRING
      else:
        self.format_string = self.FORMAT_STRING_ALTERNATIVE
```

So IIRC there were some keys, or some scenarios where you could have name of the registry key twice in the output, and this was a way not to have it '[KEY] Something KEY' , but I'm not 100% sure. Could also have been due to alternative outputs, as in when using `preg.py` to produce the output.

**Comment by joachimmetz** [comment]
@kiddinn thx for the additional context. IMHO at this point we are safe to remove this then.

**Comment by kiddinn** [comment]
I think it is safe to remove at this point.

**Comment by joachimmetz** [comment]
Removing FORMAT_STRING_ALTERNATIVE as part of https://github.com/log2timeline/plaso/issues/444
