### ISSUE TITLE
Issues with dependencies check on Debian installation

### ISSUE THREAD

**Issue by werz-svg** [log2timeline/plaso#2861]
Hi,

Here is my command : 
`log2timeline.py --no_vss ~/Documents/output.plaso tmp/image  --workers 10`

I got this error.
`Checking availability and version of dependencies.`
`[FAILURE]	        missing: artifacts.`
`[FAILURE]          	missing: bencode.`

After reading this ticket (#2168), I updated my dependencies according to the plaso’s [requirements.txt](https://github.com/log2timeline/plaso/blob/master/requirements.txt) and I cloned the ForensicArtifacts' github. All requirements (from requirements.txt) are already satisfied but I still got the same error.

I've tried another method to check dependencies : 
`wget https://raw.githubusercontent.com/log2timeline/plaso/master/utils/check_dependencies.py`
`python check_dependencies.py`

But then I got this error : 
`Traceback (most recent call last) :`
`File "/home/squeeze/tmp/lgenv/share/artifacts_test/artficats/utils/check_dependencies.py", line 10, in <module> import utils.dependencies # pylint: disable=wrong-import-position`
`ImportError: No module named 'utils'`

**Plaso / Log2timeline version:**
Version : 1.5.1+dfsg-3

**Operating system Plaso is running on:**
I’am on Debian 9, with a virtualenv.

**Installation method:**
`apt-get -y install plaso`

**Comment by joachimmetz** [comment]
@werz-svg thx for the report

1.5.1+dfsg-3 is a VERY old (~3.5 years) version of plaso (https://github.com/log2timeline/plaso/releases/tag/1.5.1). Also not released by the Plaso project but by Debian.

The issue are likely caused because how you are installing plaso / having multiple installations of plaso on your system. Please use one of the preferred installation methods https://plaso.readthedocs.io/en/latest/sources/user/Users-Guide.html#installing-the-packaged-release.

**Comment by joachimmetz** [comment]
More than 14 days without input from reporter assuming issue has been resolved.
