### ISSUE TITLE
Add Yara Parser

### ISSUE THREAD

**Issue by dc3-plaso** [log2timeline/plaso#313]
I would like to develop a yara parser that scans every file with the given yara rules in a given directory (in the data folder).

Due to the yara library's need to memory map every file, this parser will need to write out a temp file for each one. Therefore, I propose the parser only scans files smaller than a particular size limit and have excluded files like the pagefile.sys to improve performance.

**Comment by joachimmetz** [comment]
A couple of initial questions:

* Why do this as a parser in log2timeline?
* How do you plan to store the results?

**Comment by dc3-plaso** [comment]
- Yara needs access to the file object to analyze its data. Therefore a parser which gets direct access to the file object would be better, as opposed to an analysis plugin. By making it a parser, it can inherit all the advantages of the plaso/dfvfs framework's ability to scan numerous different file types. As well, we can cross reference the results of the yara parser with the other events very easily through an analysis plugin or by hand.

- A yara event object would be a non-timestamp event type (using the "NONE_TIMESTAMP") that would have two attributes: "rule_file" and "rule" Which represent the file path location of the .yara rule files and the name of the rule inside the file respectively. The rule files will be stored in a "yara_rules" folder located in the "data" folder. We can perhaps also provide a CLI helper which allows the user to provide a different location for the rules directory.

**Comment by joachimmetz** [comment]
> A yara event object would be a non-timestamp event type (using the "NONE_TIMESTAMP")

I'm not a fan of this approach but pending storage redesign this might be one of the options for now. I was thinking about using event tags instead, e.g.

* run the yara parser first (similar to hasher)
* store the results in the parser mediator
* tag or append the hits to the event objects produced for the file/data stream

**Comment by dc3-plaso** [comment]
That could also work. I could make it a hasher. It would save the effort of reading down the file multiple times if someone wants both the yara hits and a hash.

From reading the _HashFileEntry() function in worker.py, it looks like I could make a yara hasher object and have the digest be a dictionary of rule_file -> [list of rules]  which would be tagged to the events. (Would this cause issues with the serializer?) 

We would then need to rename the "hashers" to something else.

**Comment by joachimmetz** [comment]
I've asked @Onager to chime in as well, since he designed the hasher.

> This could lead to problems when there are no filestat events

Agree there are a couple of different efforts in progress to address some of these short comings:

* https://github.com/log2timeline/plaso/issues/102
* https://github.com/log2timeline/plaso/issues/321

**Comment by Onager** [comment]
I've been thinking a lot about this, and I'm not sure of the best way to add this feature. Some thoughts:

*  Something like a hasher makes some sense, because yara doesn't emit any events, but tells us something about an entire file. This sounds more like a hasher than a parser. There are a few other things that might fall into this "file analyzer" functionality - string extraction/scanning, scanning with AV etc.
*  Don't worry about the analysis plugin component of this in terms of complexity, every plugin will get every event any.
*  What encoded_stream are you referring to? There's definitely a possible issue here if yara could potentially match something that we don't produce any events for, but I'm not sure how often that would arise. Is this something you're particularly worried about?
*  I'm not particularly excited by the "copy temporary files" approach here - it's going to cause a bunch of extra I/O, a may cause failures on disk-limited systems (like, say, a Docker container). 
*  It looks like the python library can check a python string for matches against rules: http://yara.readthedocs.org/en/latest/yarapython.html which would eliminate a bunch of I/O, but still require a size limit.
*  An alternative that might accomplish some of what you're trying to achieve would be to add support for submitting files to an external service (probably checking hashes first), then collect the results later in an analysis plugin. This would work around most of the issues with doing yara in plaso itself (and also work around the yara rules distribution issue, which we haven't discussed yet). 

It might be worth moving this discussion to a design doc to review the different alternatives ("hasher"/parser/service/something else). I'm sure there's more to think about here, and as Joachim mentioned, there are a few other changes in the pipeline that might affect this.

**Comment by dc3-plaso** [comment]
* It sound like yara, "hashers", AV scanning, etc, all fall into "non-timestamp events" or artifacts (for lack of a better name). Creating a separate parser type that allows for the creation of artifacts instead of events and has support for using external services might be a good way to go.
  * For an more immediate solution, if we wanted to make it a hasher, we would need to create some guarantee that at least one event gets created for each file in order to not lose yara results.
* Agree
* The encoded_stream was a purely random example of a file type from dfvfs I picked out that has no way of getting the MAC timestamps. Depending on where the file was originally located, the file can potentially not have any MAC timestamps and therefore potential never make a single event for yara to attach its results to. While originally, this is not much of a problem because most file_entry types in dfvfs has at least one timestamp, it can become one when recursion is introduced. (Eg. a blob found in a sqlite database, or a base64 encoded file in a plist)
* Agreed.
* Yes, but then your obviously limited by RAM. It would be nice if we could somehow take advantage of yara's memory mapping, but dfvfs does not provide a file descriptor obviously.
* See my first bullet.

**Comment by Onager** [comment]
This going to be implemented in 1.5

**Comment by Onager** [comment]
Added in https://codereview.appspot.com/306720043/
