### ISSUE TITLE
l2tcsv no longer contains hash values as part of the extra field

### ISSUE THREAD

**Issue by madsumm** [log2timeline/plaso#3188]
**Description of problem:**

I had always put in the parameters --parsers md5,sha256 for the log2timeline.py. It always generate the hashes. But for this new version of Plaso, the hashes are missing from the Psort.py reports.

**Command line and arguments:**

-- parsers md5,sha256 --hasher_file_size_limit 20480000

**Plaso version:**

20200717
**Operating system Plaso is running on:**

MacOS running VirtualEnv or Ubuntu 18.04

**Installation method:**

Using VirtualEnv, pip3 install -r requirements
python3 setup.py build
python3 setup.py install

**Comment by joachimmetz** [comment]
did you mean `--hashers md5,sha256`? can you add your full log2timeline and psort command?

**Comment by madsumm** [comment]
Hi, sorry yes... its:
`log2timeline.py --hashers md5,sha256 --hasher_file_size_limit 20480000 <Plasofile> <sourceimage>`

**Comment by madsumm** [comment]
Psort command is:
`psort.py -o l2tcsv -w <csvfile> <Plasofile>`

**Comment by joachimmetz** [comment]
l2tcsv only supports a limited amount of output fields https://forensicswiki.xyz/wiki/index.php?title=L2T_CSV where were these hashes before in the extra field?

**Comment by madsumm** [comment]
I belief they were use to be part of the "extra" field?

**Comment by joachimmetz** [comment]
Do you recall which version you were using before?

A different output format like rawpy should show you all the event values including the hashes

**Comment by joachimmetz** [comment]
So these values were part of the event data before (a couple of versions ago), but for de-duplication purposes they have been move to event data stream and are stored only once per data stream now. The l2tcsv output prints unformatted event data values as part of extra. However these fields are current not considered part of the event data and therefore not printed.

As part of a larger output module clean up:

* add event data stream attributes back to l2tcsv extra
* address todo in about strange logic l2tcsv https://github.com/log2timeline/plaso/blob/master/plaso/output/l2t_csv.py#L144
* define hashes as output fields for dynamic output: https://plaso.readthedocs.io/en/latest/sources/user/Output-and-formatting.html#dynamic-output-module-fields

**Comment by madsumm** [comment]
Hi, Thanks. So the only way now is to use Dynamic output from psort and try to add the additional field for md5 and sha256 as part of the report. I will try to mimick the l2tcsv but add the 2 fields.
The hashes are really helpful and I don't want to miss it on the newer versions of Plaso.
Thanks.

**Comment by joachimmetz** [comment]
As I indicated l2t_csv has a limited number of fields, technically we are misusing extra for fields that the format does not support. It also has no ISO 8601 date and time values with second only precision. I would strongly recommend stop using it.

Dynamic is the replacement for l2t_csv since the beginning of Plaso and supports you to specifying the fields you want to output. https://plaso.readthedocs.io/en/latest/sources/user/Output-and-formatting.html#dynamic-output-module-fields

Others have indicated that they use `--fields date,time,timezone,MACB,source,sourcetype,type,user,host,short,desc,version,filename,inode,notes,format,extra -o dynamic` to mimic l2tcsv without its limitations. **Note that I've not tested this.** 

Work is in progress to change the output field handling to support some additional features see https://github.com/log2timeline/plaso/issues/2940

**Comment by joachimmetz** [comment]
To add the MD5 and SHA-256 hashes to the dynamic output `-o dynamic --additional_fields md5_hash,sha256_hash`

**Comment by madsumm** [comment]
Hi,

Its works well with customised fields and dynamic fields.
Thanks!

**Comment by joachimmetz** [comment]
Changes merged, closing issue.
