### ISSUE TITLE
Allow plaso tools only install

### ISSUE THREAD

**Issue by ptitdoc** [log2timeline/plaso#3239]
**Description of problem:**

It would be great if we could install plaso tools only with limited dependencies.

For example on some cases I already have a .plaso file and I don't need parsing evidences.

Would it be possible to include a "tools only" option in setup.py that install psort.py and pinfo.py with limited dependencies requirements?

**First throughs**

* It seems complicated seeing the current code base and dependency graph.

* Most parsers are not needed for psort and parsers seems to be the most troublesome pieces of code to compile.

* This is probably a stupid request because we have docker, packaging, pip... If it seems too complicated just forget about it.

**Comment by joachimmetz** [comment]
The reason for Plaso to bundle log2timeline.py and psort.py is that historically it was one tool log2timeline.pl. Pinfo.py has been an addition to to help getting additional information from the storage file.

We have thought about moving the storage out of Plaso into https://github.com/log2timeline/acstore 

A "tools only" option will be quite involved since parts of Plaso core and several dependencies would be still needed to run the tools.

However technically the Plaso source does not force you to have the dependencies. Only when you try to run log2timeline.py or psteal.py (or using --troubles) a dependency check is performed (or when the parsers sub module is imported). You can try if you can install the Plaso source (without dependencies) and run pyinfo.py. Psort will likely require some of the dependencies but not all parsers.

**Comment by joachimmetz** [comment]
Closing issue assuming question has been answered
