### ISSUE TITLE
GetTestFileEntry definition missing from winreg_plugins/test_lib.py

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#389]
Method is called in _OpenREGFRegistryFile, but not defined in the file.

Given that _OpenREGFRegistryFile doesn't seem to be called, this could also be fixed by removing that method.

**Comment by joachimmetz** [comment]
Given that _OpenREGFRegistryFile doesn't seem to be called, this could also be fixed by removing that method.

Not sure what you mean, but I think you might be looking at an intermediate state after https://codereview.appspot.com/274160043/ the code should use:

```
grep -r _OpenREGFRegistryFile *
tests/dfwinreg/regf.py:  def _OpenREGFRegistryFile(self, filename):
tests/dfwinreg/regf.py:    registry_file = self._OpenREGFRegistryFile(u'NTUSER.DAT')
...
tests/dfwinreg/regf.py:    registry_file = self._OpenREGFRegistryFile(u'NTUSER-WIN7.DAT')
```

And _GetTestFileEntry is defined in: tests/dfwinreg/test_lib.py
