### ISSUE TITLE
memory consumption

### ISSUE THREAD

**Issue by aozsyn** [log2timeline/plaso#4]
I've not been able to get in and debug precisely why, but memory consumption on processing Windows 7 machines is rather high.  On a 20-core, 20GB machine Plaso has 11 of 17 workers that are consuming more than 500MB apiece, two peaking out at 1.2GB and totaling 14GB.  It almost appears that workers are taking a page from Perl's book and being memory packrats - once they move on from parsing a given file they still hold on to a large amount of memory.

For the particular image I'm processing right now, I've had to kick up to the 20x20 resources, 10x10 was too small even for --workers=5.  Sorry I don't have more concrete info right now, but hopefully in the future consumption will drop a bit to make more reasonable machines useful.

**Comment by ge0rg** [comment]
Any news on this? I've tried the 1.2.0 release from the stable sift ubuntu repo on a 150GB Win7 image, and it thrashed out on a 16GB RAM machine with 40GB+ of swap.

Unfortunately, the python-plaso 1.2.1-dev-20150121-1ubuntu1~trusty package is broken (only documentation files inside), and building plaso from git is insanely complicated - do you have a .deb file of the current nightly/rc1 state?

**Comment by ge0rg** [comment]
P.S: when the workers get OOM-killed, log2timeline seems not to gracefully handle that, as it keeps on running without doing anything any more.

**Comment by joachimmetz** [comment]
> Any news on this? I've tried the 1.2.0 release from the stable sift ubuntu repo on a 150GB Win7 image, and it thrashed out on a 16GB RAM machine with 40GB+ of swap.

The previous memory issue has been fixed in 1.2.0, so I'm not sure what issue you are encountering.

Can you follow the steps mentioned in this issue and on: https://sites.google.com/a/kiddaland.net/plaso/developer/troubleshooting and determine what might be causing the memory issues on sift.

Also since I cannot look into your head or what configuration you are running on, you have to be more specific.

* what are the versions of the dependencies
* what is the command you are running
* what is the image format
* are you processing VSS?
* any other relevant details?

> Unfortunately, the python-plaso 1.2.1-dev-20150121-1ubuntu1~trusty package is broken (only documentation files inside)

Known issue, will be fixed when the next dev package is pushed.

> and building plaso from git is insanely complicated

if you want it easier, I opt to contribute to the project, and improve what you don't like

**Comment by ge0rg** [comment]
Thanks for the prompt reply.

> Can you follow the steps mentioned in this issue and on: https://sites.google.com/a/kiddaland.net/plaso/developer/troubleshooting and determine what might be causing the memory issues on sift.

Unfortunately, when the condition occurs the PC either becomes unresponsive for several hours until OOM kicks in, or I have to reboot. Do you have suggestions which one of the different approaches to follow?  Single-process? Mounting the image? Everything from the page?

> * what are the versions of the dependencies

	binplist              0.1.4-0ubuntu1
	ipython               2.3.0-2
	libbde-python         20141023-1ubunt
	libesedb-python       20141110-1ubunt
	libevt-python         20141026-1ubunt
	libevtx-python        20141112-1ubunt
	libewf-python         20140608-1ubunt
	libfwsi-python        20141116-1ubunt
	liblnk-python         20141026-1ubunt
	libmsiecf-python      20141025-1ubunt
	libolecf-python       20141026-1ubunt
	libprotobuf8:amd64    2.5.0-9
	libqcow-python        20141201-1ubunt
	libregf-python        20141030-1ubunt
	libsmdev-python       20141021-1ubunt
	libsmraw-python       20141026-1ubunt
	libtsk                4.1.30.3-1ubunt
	libvhdi-python        20141021-1ubunt
	libvmdk-python        20141021-1ubunt
	libvshadow-python     20141023-1ubunt
	libyaml-0-2:amd64     0.1.6-3
	python-bencode        1.0-1
	python-construct      2.5.1-1
	python-dateutil       2.2-2
	python-dfvfs          20141220-1ubunt
	python-dpkt           1.8-1ubuntu3
	python-hachoir-core   1.3.3-4
	python-hachoir-metada 1.3.3-2
	python-hachoir-parser 1.3.4-2
	python-protobuf       2.6.1-1
	python-psutil         2.1.1-1+b1
	python-pyparsing      2.0.3+dfsg1-1
	python-six            1.9.0-1
	python-tz             2012c+dfsg-0.1
	python-yaml           3.11-2
	pytsk3                4.1.30.3-1ubunt

> * what is the command you are running

Unfortunately I had to hard-reset the machine as it did not recover from
thrashing overnight, so the exact command line I ran got lost. I've been
rerunning with:

	log2timeline.py -d --logfile log2timeline-log.txt --workers 4 vss8-run.dump harddisk-image.000

However, it segfaulted in the olecf parser (I can make that a separate libolecf issue or upgrade to git), so I still need to reproduce the OOM condition.

> * what is the image format

a raw image of a complete SSD (obtained by afffuse on a raw splitfile set). Now I'm running l2t directly on the .000 file.

> * are you processing VSS?

Yes, l2t offered me a dozen VSSes, and I selected a single one from two weeks ago.

> * any other relevant details?

Running the trusty binaries from http://ppa.launchpad.net/sift/stable/ubuntu on Debian SID.

> if you want it easier, I opt to contribute to the project, and improve what you don't like

While I am guilty of this sin myself, outdated and confusing developer
documentation is a huge hurdle to potential contributors. When setting
up plaso, I encountered the following problems which I can not really
fix myself, and I hope you might be able to address:

 * plaso.kiddaland.net has many links to google code instead of github
 * http://plaso.kiddaland.net/developer/building-the-tool/linux overflows the reader with information, most of which is for the dependencies and not for plaso itself. It is also rather confusing if I want a mixed build (i.e. compile plaso myself, but use DEBs for the dependencies)
 * there is no documentation on how to build python-plaso.deb (and `config/dpkg/debian/changelog` is still as of 1.1.0)
 * setup.py failed due to missing plaso_extract_search_history.py (was fixed today)

**Comment by joachimmetz** [comment]
>  http://plaso.kiddaland.net/developer/building-the-tool/linux overflows the reader with information, most of which is for the dependencies and not for plaso itself. It is also rather confusing if I want a mixed build (i.e. compile plaso myself, but use DEBs for the dependencies)

What for you might be too much, is too little information for another. The challenge is also that people read one page but don't read the information relevant for them that is on another. E.g. the page you are looking for how to build a deb of plaso is intended for setting up plaso for development for which there is no need to build a deb of plaso. So in my perception you are saying there is too little information where on the other hand you just said there is too much. So unless you have concrete things you want to change here I cannot do much with these remarks.

> setup.py failed due to missing plaso_extract_search_history.py (was fixed today)

As mentioned here: https://sites.google.com/a/kiddaland.net/plaso/home/releases-and-roadmap

**Note that the development release is for development, expect frequent updates and potential breakage.**

Or is this text too large and too confusing for you as well? Hope you get my point that the value of documentation also depends on how it is read.

> Running the trusty binaries from http://ppa.launchpad.net/sift/stable/ubuntu on Debian SID.

These are different distros, doing this is asking for problems. Also there seem to be versions of dependencies that are too old for version 1.2.0 of plaso (meaning have known issues that have been fixed). Please ask the sift maintainers to fix that. I'm also wondering if this is the reason for the issues you are experiencing.

> Do you have suggestions which one of the different approaches to follow?  Single-process? Mounting the image? Everything from the page?

As with most all troubleshooting try to rule out possible causes. In this case maybe first try to rule out the role of VSS. So mount the split raw, mount the individual VSS, see if log2timeline still consumes a lot of memory or try running log2timeline on the current volume only.

However I would really recommend setting up a clean environment first and maybe stick with Ubuntu instead of trying yourself on Debian.
