### ISSUE TITLE
log2timeline.py add file based status view

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#4464]
For Turbinia have log2timeline.py track status (header) in a file

**Comment by joachimmetz** [comment]
@aarontp FYI

**Comment by aarontp** [comment]
Awesome, thanks!  Yeah, having even just a single status line would be great for Turbinia since we can put it right into the Turbinia Task status.

FYI @wajihyassine this is related to what we were talking about the other day (good ways to get the current running status of long running Plaso Tasks).
