### ISSUE TITLE
MFT parser yielding insufficient data?

### ISSUE THREAD

**Issue by JohnnieWalker16** [log2timeline/plaso#595]
Hi,
The MFT parser pretty goods comparing to alternatives, but it has 2 major drawbacks can't figure how to circumvent, making it nearly irrelevant: it doesn't specify file's absolute path (didn't find any switch to request this kind of info) and the file name presented is the DOS 8.3 short name instead of the long name. 

Tried to circumvent the last one using pylibfsntfs but failed. 

Is there any way, without rewriting the parser obviously, to get this information?

**Comment by joachimmetz** [comment]
>  it doesn't specify file's absolute path

First of all it is debatable if path reconstruction without the $I30 indexes is a reliable method at all. Some tools attempt it now and do a reliable job for the "regular" case. Though I have not found a detailed description about the pitfalls by any of them e.g. correctly dealing with the sequence number.

When time permits we'll introduce the concept of "path hints" to add this information in a (hopefully) conceptually better terminology.

> and the file name presented is the DOS 8.3 short name instead of the long name.

Both the long and short file name should be there since the MFT entries are parsed on a per attribute-basis. We are thinking about adding grouping in the analysis phase where we e.g. combine $I30 and $MFT based file entry information into a single event and detect anomalies.

> Tried to circumvent the last one using pylibfsntfs but failed.

Plaso's $MFT parser uses pyfsntfs see: https://github.com/log2timeline/plaso/blob/master/plaso/parsers/ntfs.py#L195

**Comment by JohnnieWalker16** [comment]
I meant i tried accessing the long name using pyfsntfs manually to figure how to "make it" show the long name, something like

`entry = mft.get_file_entry(arbitrary_entry_number) # guessed it`
`fn_attr = entry.get_attribute(file_name_attr_number) # looked for it`
`print fn_attr.name`

Always gave me short file names, for every file entry i tried. What am i missing?

Thanks for the comment about the full path. I surely have some reading to do...

**Comment by joachimmetz** [comment]
There are multiple FILE_NAME attributes, you have to check them all. This will also include hard links.

**Comment by JohnnieWalker16** [comment]
Got the idea about the multiple $FILE_NAME attributes.
Went back to my timeline and found that 25% of the MFT events originated in DOS namespace attributes, which should be (and are, in my sample at least) exactly the same as the Windows namespace attribute. 
I think truncating both attributes (assuming they are identical for all other parameters) into single event (for each timestamp) can ba helpful. 

Assuming we have the whole disk image, it should be possible to assemble the full path, shouldn't it?

**Comment by joachimmetz** [comment]
> I think truncating both attributes (assuming they are identical for all other parameters) into single event (for each timestamp) can ba helpful.

Not at parsing phase, we are considering this in analysis phase. Where we can say something in line of:
....
file modification event X is described by MFT entry A (with 8.3 name), MFT entry B (with long name), $I30 entry C (with 8.3 name), ...
....

This model would allow us to more complex things e.g. like mapping file system paths with e.g. shell item-based paths.

> Assuming we have the whole disk image, it should be possible to assemble the full path, shouldn't it?

Yes but you are specifically talking about a MFT parser; as in its name parses the $MFT file not the $I30 of other NTFS file system metadata.

If you want full paths you can use filestat for now. Work is in the pipeline to add NTFS attribute information to filestat as well.

**Comment by JohnnieWalker16** [comment]
Got it. Thanks!
