### ISSUE TITLE
timesketch output add Elasticsearch 2.x support

### ISSUE THREAD

**Issue by berggren** [log2timeline/plaso#607]
_timeline attribute is not supported for Elasticsearch 2.x.
We do not need it so lets just remove the mapping.

* [x] timesketch output add Elasticsearch 2.x support
* [x] Close open elastic search related issues:
  * ~~https://github.com/log2timeline/plaso/issues/172~~
  * ~~https://github.com/log2timeline/plaso/issues/47~~
  * ~~https://github.com/log2timeline/plaso/issues/197~~
  * ~~https://github.com/log2timeline/plaso/issues/676~~
  * ~~https://github.com/log2timeline/plaso/issues/677~~

**Comment by joachimmetz** [comment]
Per discussion assigning to @Onager

**Comment by rodgermoore** [comment]
> Remove non-timesketch elastic search output module?

Please keep in mind some end-users are using other front-ends with their data. I use Kibana a lot. Needing to use the Timesketch output module to use be able to use ES with another front-end is a bit confusing not? Why not keep the generic ES output plugin (name) to use with Timesketch and other frontends (Kibana, Grafana, whatever).

Tnx

**Comment by joachimmetz** [comment]
The comment is there for the following reason:

If the output module is not maintained, it will be broken, so is it better to keep a broken output module or just drop the entire functionality. If we don't hear from plaso users, we cannot assess if people are using the functionality. Since we are not using it, it makes more sense from our point of view (POV) to drop the support.

So if you (in general) have a need for the output module, make sure to let us know you do use and and feel free to help us maintain it.

**Comment by rodgermoore** [comment]
> If the output module is not maintained, it will be broken, so is it better to keep a broken output module or just drop the entire functionality? If we don't hear from plaso users, we cannot assess if people are using the functionality. Since we are not using it, it makes more sense from our point of view (POV) to drop the support.

That makes a lot of sense from your point of view as developers. It's too bad you didn't get feedback from users using this functionality.  Looking from my personal experience, the huge increase of popularity and increase of analytical possibilities on the Elasticsearch, Logstash, Kibana stack, I would really find it a pity when the ES output module gets dropped from Plaso.

> So if you (in general) have a need for the output module, make sure to let us know you do use it and and feel free to help us maintain it.

I use it! I would like to help maintain the module but I'm afraid my help can only be in the domain of testing Plaso and configuring Elasticsearch and creating dashboards in Kibana. My Python programming skills are (atm) too novice to deliver Python code for Plaso. 

Timesketch is great but I would like to mention why in some cases I prefer Kibana 4 over Timesketch. It is mainly because of the (dynamic) visualizations in Kibana. All data visualizations are linked on the dashboard, navigating and searching through the data this way is extremely efficient and powerful.

Maybe users are not aware of the enormous analytical potential of Plaso in combination with ELK? If you want me to write a (new) blog or make a (Youtube) tutorial about how to use Plaso in combination with the ELK stack I would be very pleased to do be of support this way.

**Comment by joachimmetz** [comment]
>  I would really find it a pity when the ES output module gets dropped from Plaso.
> I use it!

Great good to know, we'll keep this in mind, at the moment we are still evaluating if we should drop it.

> My Python programming skills are (atm) too novice to deliver Python code for Plaso. 

1. Testing release candidates is already helpful.
2. You only learn programming by doing it.
3. Basic maintenance does not require elaborate programming skill, it typically means changing things that are broken. The code review process is there to improve code consistency.

> Timesketch is great but I would like to mention why in some cases I prefer Kibana 4 over Timesketch.

Make sense, Timesketch has a different scope/focus than Kibana

> Maybe users are not aware of the enormous analytical potential of Plaso in combination with ELK?

Could be.

> If you want me to write a (new) blog or make a (Youtube) tutorial about how to use Plaso in combination with the ELK stack I would be very pleased to do be of support this way.

Yes please, that is also very helpful; also if you want we can (re)post it on http://blog.kiddaland.net/.

**Comment by clausing** [comment]
Count me in for keeping the generic ES output module. +1 for Kibana compatibility

**Comment by rodgermoore** [comment]
> If you want me to write a (new) blog or make a (Youtube) tutorial about how to use Plaso in combination with the ELK stack I would be very pleased to do be of support this way.

>_Yes please, that is also very helpful; also if you want we can (re)post it on http://blog.kiddaland.net/._

I am working on this.

**Comment by n3uroblast0ma** [comment]
I already see two people above me pledging support, but I would also like to throw my hat in the ring for keeping the ES output module. ELK is really awesome at exposing data in unique ways, and it would be awesome to be able to output Plaso results directly into an ES database.

If you need help maintaining it, I would be willing (granted I'm not a seasoned developer by any means).

**Comment by Onager** [comment]
@berggren has kindly offered to maintain and rewrite the Elasticsearch module, so reassigning to him

**Comment by rodgermoore** [comment]
Just a quick reminder. Psort still has the "json_line" output option. Assuming the "json_line" output generates the same dataset as the "elastic" output, the json_line generated file is very easy to process using Logstash.

Logstash gives you advanced control over how and what kind of data you want to import into Elasticsearch. Using "json_line" and Logstash you can import your data into any Elasticsearch version you want. 

I am working on a Plaso - ELK video tutorial and I will include the "json_line" option as well.

**Comment by enhanced** [comment]
+1 for continued ES support, not sure if I have my pyhon borked or what, but I can't run the ES output natively.. blows up as: ```AttributeError: 'dict' object has no attribute 'startswith'```

**Comment by muhamadli302** [comment]
> So if you (in general) have a need for the output module, make sure to let us know you do use it and and feel free to help us maintain it.

@joachimmetz My team and I do want to use the Elasticsearch output, it will be great for us.
Also we're not professionals with python, but if there's any way to help let me know.
Thank you

**Comment by joachimmetz** [comment]
@muhamadli302 I've asked @berggren and @Onager to let you know more on the status of Elasticsearch output. If everything goes according to plan this should be fixed in 1.5.0 and you can help by testing upcoming release candidates. We'll announce a feature freeze likely end of month/beginning of next month.

**Comment by Onager** [comment]
@muhamadli302 This is under control, and @berggren is planning to work on this next week. We'd appreciate your help in testing once we have some more code.

**Comment by berggren** [comment]
The new output module has been pushed to master. Please test if possible.
Main CL: https://codereview.appspot.com/301030043/
Raw files mapping CL: https://codereview.appspot.com/299550043

**Comment by joachimmetz** [comment]
All tasks completed
