### ISSUE TITLE
--serializer-format json 

### ISSUE THREAD

**Issue by dnides** [log2timeline/plaso#86]
When I run the the following command (Windows x64 1.2.0 RC2) to invoke serialization format from protobufs to JSON - I do not get a json in the output as expected. Look at attached picture - example of output.

C:\Users\dnides\Downloads\plaso>log2timeline.exe --serializer-format json d:\export3.json "d:\Test_Data\Evil\4Dell Latit
ude CPi.E01"

![capture](https://cloud.githubusercontent.com/assets/1940071/5811550/47be67de-a01e-11e4-8bfd-b74bd6a1b098.JPG)

**Comment by kiddinn** [comment]
yes, just to clarify the "serializer-format" has nothing to do with the output being JSON, it just refers to that the event object serialization format is JSON instead of PROTO, still the same storage format, still the same ZIP file with all the same structure. This is just a speed improvement since JSON serialization is considerably faster than protobufs.
