### ISSUE TITLE
log2timeline performance improvements

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#906]
* [x] Improve performance
  * ~~https://codereview.appspot.com/303310043/~~
  * ~~https://codereview.appspot.com/303420043/~~
* [x] ~~Have a closer look at the merge depletion behavior~~
  * ~~one option would be to prioritize directories before files~~
  * ~~preserve merge order or have a similar approach as the task heap sort for the merges~~
  * ~~remove pending merge tasks from update loop~~
* [x] ~~profile memory consumption of main process during multi processing~~
  * ~~Investigate high memory usage during merge~~
  * ~~main process peak memory usage on small test image: 200 M~~
  * ~~on larger image: 400 M~~

**Comment by joachimmetz** [comment]
without directories first sorting
```
profile name	number of samples	total CPU time	total system time
merge	1382239	224.320985	221.172611952
merge_check	21467	368.16631	363.295666218
get_event_source	21468	3.70441	3.734326601
schedule_task	18675	0.545628	0.543790102
process_sources	1	374.554704	369.641835928
```

with directories first sorting
```
profile name	number of samples	total CPU time	total system time
merge	569989	232.36187	227.889906645
merge_check	20871	323.389096	319.030747175
get_event_source	39547	2.777892	2.6817982197
schedule_task	18675	0.65058	0.6608076096
process_sources	1	329.632358	325.102949858
```

**Comment by Onager** [comment]
Are there still things that need to happen for 1.5 here?

**Comment by joachimmetz** [comment]
I opt to leave open for now, and see how RC2 behaves.

**Comment by daniel-ayers** [comment]
Could this issue be the same one I am seeing where log2timeline.py is painfully slow and ends up with the main process at 100% utilisation and placing only a few entries in the workers queue per second, with the result that the workers are lining up for work and mostly idle?

strace -p PID -tt reveals the main process is constantly executing stat() system calls against about 2,600 files "tmpdir/merge/[0-9a-f]*.plaso" in the temp directory.  Horribly inefficient as the system wastes most of its time parsing the same (Linux fs) path names over and over again.

If this is a different issue, pls let me know and I will open a fresh issue for it with full detail.  But didn't want to open a duplicate when I was unsure.

**Comment by daniel-ayers** [comment]
BTW the main process in this instance is using about 800mb virtual space with about 350mb resident with a 500Gb source image.

**Comment by joachimmetz** [comment]
> Could this issue be the same one I am seeing where log2timeline.py is painfully slow and ends up with the main process at 100% utilisation and placing only a few entries in the workers queue per second, with the result that the workers are lining up for work and mostly idle?

yes this is related. The merge is time consuming and if there are no tasks for the worker they'll sit idle.

> Horribly inefficient as the system wastes most of its time parsing the same (Linux fs) path names over and over again.

Not sure I understand what you are trying to tell me here? This is not the root cause of the bottleneck.

**Comment by daniel-ayers** [comment]
Well I don't know what the bottleneck is, aside from observing the process is CPU bound.  Since you are talking about merging I can guess there is some sort of merge operation going on.

During a ten second period the main process I am watching here executed the stat() system call 70056 times against 2666 different files in tmpdir/merge.  My point is with context switches into and out of kernel plus reparsing the file paths over and over again that's quite a bit of work - and given that of those 2666 files only about 20 of them have been modified in the last five minutes it doesn't seem necessary to check them 7,000 times a second.

This may not be the bottleneck but reducing the wasted cycles will free up more cycles to get the main job done.

**Comment by joachimmetz** [comment]
If you have a better solution without blocking IPC, let us know.

**Comment by daniel-ayers** [comment]
I'm not across exactly what the code is trying to do but off the top of my head I would consider splitting the files in the merge dir (*see comment below*) into X subdirs, maybe with X=16 based on the first hex digit of the filename.  Use open(O_PATH) to get a dirfd for all X of them and store them.  

Now you can detect a new file in one of the subdirs by polling via fstatat(dirfd_X) and detecting the directory being updated.  You could poll all X dirs every time interval (say 0.25 sec).  And if you wanted to detect files being updated you could choose one subdir each time interval and fstatat()/etc the contents to detect changes.

*comment*: Using open(O_PATH) and *at() functions means the OS doesn't have to keep parsing the fs right from the root for each file.  If the fs is ext4 its pretty efficient, but for other file systems the difference can be significant.  Note that performance problems associated with parsing from root are compounded if there are symlinks or mount points.

My point is that the FS is just a data structure like any other so you want to put things in there so that its easy to get them back out again - and hopefully getting the fs to do the hard work for you.

That's my suggestion, FWIW, given I'm not totally across this code and nor am I a python expert. :)

Libevent (which does have python bindings) may also have some application.

**Comment by joachimmetz** [comment]
Yeah but this will only provide for a a marginal optimization, likely a couple of % on average. You can run log2timeline with a profiler and get the numbers. The major bottleneck is "the merge depletion behavior".

**Comment by daniel-ayers** [comment]
I suspect the difference could be quite major if there are network file systems or clustered file systems involved.  For example on nfs if each stat() turns into a RPC or on Lustre if the MDS is queried.  7000 of those a second will ruin your day.  People with diskless worker nodes might be unhappy.

I will do some tests to try to quantify the issue - if, in fact, there is an issue at all.

**Comment by joachimmetz** [comment]
But serious. If you really want performance why run on a slow network file system? Why not get an SSD or use a RAM disk? Also the merge depletion will still happen and the merge will be even slower, percentage wise the impact is still similar.

The current plaso is not built for diskless systems. All these sound like arguments to me that you really want to make your point. Getting the number sounds like the most constructive option here, also onager@ is working on some changes that might affect this behavior.

**Comment by daniel-ayers** [comment]
Sorry, it sounds like my input isn't helping.  I'm considering situations where I need to take tools into client environments (environments where the data can't be taken away, for various reasons) and those environments were not designed specifically for processing forensic workloads.  I'll drop it.

**Comment by joachimmetz** [comment]
> I'm considering situations where I need to take tools into client environments

Don't get me wrong I appreciate the feedback, but as indicated, please consider the entire problem scope and not get stuck on a narrow subset of it.

**Comment by Onager** [comment]
The change above was to cache results for tasks that are known to be ready to be merged. This should drop the number of stat() calls being made. In a test for an averagely bad situation, with lots of small files with a low number of events, performance increased by ~10%.

**Comment by joachimmetz** [comment]
This is a ball park figure, and will vary a lot on a per run basic.

**Comment by joachimmetz** [comment]
```
profile name	number of samples	total CPU time	total system time
merge	1860522	255.991836	255.775858402
merge_check	21769	338.829064	339.073741198
get_event_source	40445	2.701654	2.7028772831
schedule_task	18675	0.584931	0.6130464077
process_sources	1	345.067381	345.262303829
```

**Comment by joachimmetz** [comment]
```
profile name	number of samples	total CPU time	total system time
merge	18675	215.52026	212.640216589
merge_check	21920	340.326093	337.319605827
get_event_source	40596	2.168409	2.0391337872
schedule_task	18675	0.667539	0.6661407948
process_sources	1	345.79006	342.54080987
```

**Comment by joachimmetz** [comment]
Removing 1.5 release milestone and added blocking label. Storage refactor/replacements it blocking further performance improvements.

**Comment by joachimmetz** [comment]
Closing this issue. Storage refactor and optimize merge behavior are addressing part of this issue.
