### ISSUE TITLE
Difficult/Slow to get yara results from plaso storage file

### ISSUE THREAD

**Issue by ghost** [log2timeline/plaso#923]
This may be some combination of a question & a feature request. :) And it may be the answer will be 'wait for a storage redesign'.

I have read https://github.com/log2timeline/plaso/issues/313 (noting the discussion about how to represent yara hits) and browsed through the code review for the yara additions.

Yara matches are currently represented as attributes of time-stamped events.

As far as I have been able to work out ... if I wanted to know if there was any 'badness' (defined by yara rules) in an image I would need to run l2t and then try to use psort.py to find out if there were any yara hits.

The psort phase won't be very efficient because there are likely to be multiple events with the same yara hits (from the one file) and psort wants to spend a lot of time sorting those events into chronological order - when I might not care about the events themselves or the associated time stamps.

Seems that on the psort command line a filter like 'yara_match != ""' would be needed - a bit clunky?

Is that how things stand at present - or have I missed something?

**Comment by Onager** [comment]
Yep, this isn't ideal, and some storage changes here could be quite helpful. Ideally, we'd apply the yara match attributes to a file, rather than all the events derived from it. 

I've added some flags to at least make outputting yara fields a little less painful, but an analysis plugin would also be helpful. I'll put something together for 1.6.

For the use case you mention here though, if you just want to know if any files match yara rules and don't care about the actual events, running yara directly would seem to be the way to go.

**Comment by joachimmetz** [comment]
Bumping this one milestone due to pending event data storage changes

**Comment by joachimmetz** [comment]
@Onager close issue? Unclear what you want to "enhance" here

**Comment by Onager** [comment]
The enhancement would be supporting filtering for Yara match in Psort. 

This isn't going to make the release, removing from milestone.

**Comment by joachimmetz** [comment]
Moved FR to https://github.com/log2timeline/plaso/issues/3040, closing issue.
